export const GET_POSTS_LOADING = 'GET_POSTS_LOADING';
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const GET_POSTS_ERROR = 'GET_POSTS_ERROR';
//
export const SET_SEARCH_DATA = 'SET_SEARCH_DATA';

export const CONCAT_SEARCH_DATA = 'CONCAT_SEARCH_DATA';